version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-patches:
        dependency-type: development
        update-types:
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
